name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Firebird
      run: sudo apt-get update -qq
      run: sudo apt-get install -qq firebird2.5-super firebird2.5-dev
      run: sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
      run: cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
      run: sudo service firebird2.5-super start

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
