name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: ['1.15', '1.16', '1.17']
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Firebird
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq firebird2.5-super firebird2.5-dev
        sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
        cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
        sudo service firebird2.5-super start

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
